---
apiVersion: v1
kind: Service
metadata:
  namespace: thanos
  name: querier
spec:
  type: NodePort 
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32750
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: querier
