apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-storegateway-pv
  namespace: thanos 
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/thanos-storegateway-pv
