apiVersion: v1
kind: Service
metadata:
  name: event-exporter
  namespace: kube-system
  labels:
    monitor: exporter
spec:
  type: NodePort
  selector:
    app: event-exporter
  ports:
    - name: http
      port: 9102
      targetPort: 9102
      protocol: TCP
      nodePort: 30912
