apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-projects
  namespace: browser
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-projects
  template:
    metadata:
      labels:
        app: nginx-projects
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: nginx-configmap
            items:
              - key: index.html
                path: index.html
