apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  labels:
    k8s-app: cadvisor
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kubelet  
  namespaceSelector:
    matchNames:
      - kube-system  
  endpoints:
  - port: https-metrics  
    path: /metrics/cadvisor
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
