apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: thanos
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: http  
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
