apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: create-user-job
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-create-user-job
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: run-airflow-migrations
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-migrate-database-job
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: scheduler
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-scheduler
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: statsd
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-statsd
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: triggerer
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-triggerer
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: webserver
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-webserver
  namespace: airflow
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.13.1
    component: worker
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-worker
  namespace: airflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: airflow
