---
# Source: logstash/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: "logstash"
  namespace: npension
  labels:
    app: "release-name-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "release-name"
  annotations:
    null
spec:
  type: NodePort
  selector:
    app: "release-name-logstash"
    chart: "logstash"
    release: "release-name"
  ports:
    - name: tcp
      port: 5064
      protocol: TCP
      targetPort: 5064
      nodePort: 30056
    - name: tcp2
      port: 5044
      protocol: TCP
      targetPort: 5044
      nodePort: 30050 

