apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: loki
  labels:
    app: promtail
spec:
  type: NodePort
  selector:
    app: promtail
  ports:
    - port: 3101
      targetPort: 3101
      nodePort: 31011
