apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cadvisor-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cadvisor-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: cadvisor
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cadvisor-cluster-role
  apiGroup: rbac.authorization.k8s.io
