apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    name: cadvisor
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http-metrics
  selector:
    name: cadvisor
