apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: thanos
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      name: cadvisor
  namespaceSelector:
    any: true
  #  matchNames:
  #  - kube-system
  endpoints:
  - port: http-metrics
