apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-prometheus-pvc
  namespace: thanos 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
