---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: thanos 
  labels:
    prometheus: main
spec:
  endpoints:
    - port: web
  selector:
    matchLabels:
      operated-prometheus: "true"
