apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: thanos
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
